### ISSUE TITLE
format coordinates to allow google .kml files

### ISSUE THREAD

**Issue by JL907** [bunzosteele/PokeWatch#10]
Currently if you make a google map with markers you can export the marker data into a .kml file.  Any way we can have .kml support?

`<Point>
                    <coordinates>-134.5482194,58.360015,0.0</coordinates>
                </Point>`

**Comment by bunzosteele** [comment]
How do you export the markers? I'd love to support this, didn't know it was a thing.

**Comment by JL907** [comment]
You can set markers in my google maps and export them

**Comment by JL907** [comment]
https://support.google.com/mymaps/answer/3024454?hl=en

Go to my google maps and create a new map. Put some markers down and in the map menu export map as .kml file. The kml file is like a xml file that contains all coordinates of the markers you placed. You can make layers too.

**Comment by JL907** [comment]
If we can get KML working that will save everyone a hell of a lot of time on manually entering coordinates

**Comment by JL907** [comment]
The new tool that was merged is a good addition but i already have maps premade with points. Any eta on kml support?

**Comment by JL907** [comment]
Or maybe a similar tool to convert kml to json

**Comment by RedSparr0w** [comment]
Can you paste some sample kml code, I will have a go at it

Sent from my iPhone

On 30/07/2016, at 5:40 PM, lemonlust <notifications@github.com<mailto:notifications@github.com>> wrote:

Or maybe a similar tool to convert kml to json

##

**Comment by JL907** [comment]
Cant do on mobile ill be home shortly, will post in a bit

**Comment by KensonN** [comment]
Here's a sample KML File: 

`<?xml version='1.0' encoding='UTF-8'?>
<kml xmlns='http://www.opengis.net/kml/2.2'>
	<Document>
		<name>San Jose Pokewatch Map 2</name>
		<description><![CDATA[]]></description>
		<Folder>
			<name>Santana Row</name>
			<Placemark>
				<name>Santana Row 1</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.94809600000002,37.321751,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Santana Row 2</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.9481027,37.319646,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Santana Row 3</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.9481778,37.3181699,0.0</coordinates>
				</Point>
			</Placemark>
		</Folder>
		<Folder>
			<name>Coyote Creek</name>
			<Placemark>
				<name>Coyote Creek 1</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.867009,37.335783,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Coyote Creek 2</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.86689100000001,37.33307,0.0</coordinates>
				</Point>
			</Placemark>
		</Folder>
		<Folder>
			<name>Overfelt Park</name>
			<Placemark>
				<name>Overfelt Park 1</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.85517400000003,37.364968,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Overfelt Park 2</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.85445500000003,37.364175,0.0</coordinates>
				</Point>
			</Placemark>
		</Folder>
		<Folder>
			<name>Plaza de Cesar Chavez Park</name>
			<Placemark>
				<name>Plaza de Cesar Chavez Park</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.88969099999997,37.332225,0.0</coordinates>
				</Point>
			</Placemark>
		</Folder>
		<Folder>
			<name>Guadalupe River Park</name>
			<Placemark>
				<name>Guadalupe River Park 1</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.91111699999999,37.35185,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Guadalupe River Park 2</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.90909899999997,37.348506,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Guadalupe River Park 3</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.90652299999999,37.345297,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Guadalupe River Park 4</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.90446300000002,37.342806,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Guadalupe River Park 5</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.90283099999999,37.340963,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Guadalupe River Park 6</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.904448,37.344568,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Guadalupe River Park 7</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.901588,37.337639,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Guadalupe River Park 8</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.90035499999999,37.336141,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Guadalupe River Park 9</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.89909899999998,37.334643,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Guadalupe River Park 10</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.898867,37.333552,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Guadalupe River Park 11</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.9076872,37.343362,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Guadalupe River Park 12</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.905992,37.3418267,0.0</coordinates>
				</Point>
			</Placemark>
		</Folder>
		<Folder>
			<name>Village Oaks Shopping Center</name>
			<Placemark>
				<name>Village Oaks 1</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.802524,37.247231,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Village Oaks 2</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.802505,37.250048,0.0</coordinates>
				</Point>
			</Placemark>
		</Folder>
		<Folder>
			<name>Berryessa Library</name>
			<Placemark>
				<name>Berryessa Branch Library</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.84095159999998,37.39414910000001,0.0</coordinates>
				</Point>
			</Placemark>
		</Folder>
		<Folder>
			<name>Noble Park</name>
			<Placemark>
				<name>Noble Park</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.8416719,37.3949031,0.0</coordinates>
				</Point>
			</Placemark>
		</Folder>
		<Folder>
			<name>Penitencia Creek Park</name>
			<Placemark>
				<name>Penitencia Creek Park 1</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.849376,37.3917006,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Penitencia Creek Park 2</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.8480241,37.3892201,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Penitencia Creek Park 3</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.8447411,37.390763,0.0</coordinates>
				</Point>
			</Placemark>
		</Folder>
		<Folder>
			<name>Emma Prusch Park</name>
			<Placemark>
				<name>Emma Prusch Park 1</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.8458462,37.3404704,0.0</coordinates>
				</Point>
			</Placemark>
			<Placemark>
				<name>Emma Prusch Park 2</name>
				<styleUrl>#icon-503-DB4436-nodesc</styleUrl>
				<Point>
					<coordinates>-121.8477345,37.3394639,0.0</coordinates>
				</Point>
			</Placemark>
		</Folder>
		<Style id='icon-503-DB4436-nodesc-normal'>
			<IconStyle>
				<color>ff3644DB</color>
				<scale>1.1</scale>
				<Icon>
					<href>http://www.gstatic.com/mapspro/images/stock/503-wht-blank_maps.png</href>
				</Icon>
				<hotSpot x='16' y='31' xunits='pixels' yunits='insetPixels'>
				</hotSpot>
			</IconStyle>
			<LabelStyle>
				<scale>0.0</scale>
			</LabelStyle>
			<BalloonStyle>
				<text><![CDATA[<h3>$[name]</h3>]]></text>
			</BalloonStyle>
		</Style>
		<Style id='icon-503-DB4436-nodesc-highlight'>
			<IconStyle>
				<color>ff3644DB</color>
				<scale>1.1</scale>
				<Icon>
					<href>http://www.gstatic.com/mapspro/images/stock/503-wht-blank_maps.png</href>
				</Icon>
				<hotSpot x='16' y='31' xunits='pixels' yunits='insetPixels'>
				</hotSpot>
			</IconStyle>
			<LabelStyle>
				<scale>1.1</scale>
			</LabelStyle>
			<BalloonStyle>
				<text><![CDATA[<h3>$[name]</h3>]]></text>
			</BalloonStyle>
		</Style>
		<StyleMap id='icon-503-DB4436-nodesc'>
			<Pair>
				<key>normal</key>
				<styleUrl>#icon-503-DB4436-nodesc-normal</styleUrl>
			</Pair>
			<Pair>
				<key>highlight</key>
				<styleUrl>#icon-503-DB4436-nodesc-highlight</styleUrl>
			</Pair>
		</StyleMap>
	</Document>
</kml>`

**Comment by KensonN** [comment]
Here's a sample KML file: http://pastebin.com/mPtYm4RQ

**Comment by JL907** [comment]
Thank you @kensonN, Layers are labled as folders in kml, any way we can have folder names be regions in json?

**Comment by KensonN** [comment]
I have no programming experience so I have no idea what you are talking about. That is, if that's addressed to me.

**Comment by bunzosteele** [comment]
I think the need for this as a tool is drastically reduced by the Configuration Generator. Someone could write a really nasty regex to get the job done though...
