### ISSUE TITLE
Add Ability to Disable PTC Login

### ISSUE THREAD

**Issue by enz1ey** [bunzosteele/PokeWatch#13]
I created a Gmail account, and I understand the benefits of having an additional PTC account, but PTC seems to always be down (I can't even create an account right now).

My application has been continuously crashing right after attempting to sign in using PTC and setting coordinates, and it's in a restart loop from that point. It would be nice to be able to disable logging in with either account you don't use.

**Comment by todamach** [comment]
Just dont type in PTC logins in configuration? That's what I do.

**Comment by enz1ey** [comment]
Obviously I didn't enter login credentials that don't exist. Regardless, the program still tries to authenticate via PTC a few times before failing back to Gmail. Have you even looked at the logs to see what happens when the program runs?

**Comment by todamach** [comment]
Ok, you're right. But it probably adds like 5 seconds max. There's much more important bug that causes crashes and down times even up to 10 minutes.

**Comment by enz1ey** [comment]
It actually adds about 2.5 minutes each time. The app crashes because PTC is totally down, and the app then waits 2 minutes to restart. Either way, I'm not asking that this be implemented as a higher priority than any actual bugs, being that it's not really a bug. It's more of a feature request, but it's probably something that logically should've been included from the beginning.

I'm not sure why you even bothered sharing your input with this, being that it's not really your responsibility to decide what features/issues are legitimate or worthy of being considered. If the dev doesn't want to add a line in the config file to disable either PTC or Gmail logins, then it's his call. Regardless, without people submitting their ideas, the app will stagnate and not receive new features. Nobody said you can only choose to either add features or fix bugs, but not both, so I don't know what your deal is.

**Comment by screenhunter** [comment]
I am getting the same issue as well, seems more like an issue to me because it does cause the app to crash

**Comment by todamach** [comment]
I just shared my point of view. No need to act so defensive.

**Comment by bunzosteele** [comment]
The app should not be crashing from failed PTC login attempts. Once it sees the credentials are missing, or tries and fails to login, it moves on to Google auth
