### ISSUE TITLE
configuration.json?

### ISSUE THREAD

**Issue by dotheknifefight** [bunzosteele/PokeWatch#15]
where is this file i'm supposed to move configuration files into? am i supposed to create it?

**Comment by canthonyscott** [comment]
download the compiled version from  (https://db.tt/6Vp3nENn). It is included in there and can be modified

**Comment by dotheknifefight** [comment]
What does it mean "Move configuration files into Configuration.json"? I downloaded the archive in the link you sent me, and edited the .json file inside. That should be all, right? What about /PokeWatch/Data.cs? I see that there are a lot of GPS coords in that file as well. Should the two match?

**Comment by canthonyscott** [comment]
Editing the Configuration.json file is all you need to do to get it running.

**Comment by bunzosteele** [comment]
Pokewatch/Data.cs is a very old file that contains hardcoded data, it was made obsolete by Configuration.json
