### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by dpbuhlig** [bunzosteele/PokeWatch#17]
I followed the setup instructions but when I start PokewatchLauncher it briefly brings up two command prompts and closes them. Task manager doesn't show it running and the tweeter account isn't tweeting. Any help is appreciated.

**Comment by dotheknifefight** [comment]
I am having the same issues. I launch the PokewatchLauncher.exe and two DOS prompts appear momentarily before going away, and nothing else happens.

**Comment by KensonN** [comment]
That usually means you have an unfinished bracket somewhere. Check the log file and see what it says.

**Comment by dotheknifefight** [comment]
as in log4net.xml?

**Comment by bunzosteele** [comment]
He is referring to the log.txt file, which will contain information about what the program was attempting to do, if both windows are closing, that means that something is likely misconfigured.
