### ISSUE TITLE
Radius check?

### ISSUE THREAD

**Issue by JL907** [bunzosteele/PokeWatch#20]
Can you add start up warnings if there are overlapping points?

**Comment by dotheknifefight** [comment]
Or perhaps the Pokemon can be reported as near or between both places?

**Comment by bunzosteele** [comment]
The program will detect if a pokemon has already been found and not tweet about it. I don't want to have warnings about overlapping points because it would require very precise placement to have 0 overlap and no holes in the coverage of an area.
