### ISSUE TITLE
Configuration.json : Unable to load config (798) (from the log file)

### ISSUE THREAD

**Issue by PastaGringo** [bunzosteele/PokeWatch#22]
Hi,

Thanks for your work :)

I only modified my PTC, Google account and Twitter App ID from the configuration.json file.
I was careful about not touching any other thing in the file to avoid some syntax error.

But when I started PokemonLauncger.exe, it stopped immediately and I can see in the log file : 

[!]Launching: Pokewatch.exe 
[-]Unable to load config.
Invalid object passed in, ':' or '}' expected. (798): {

So I took the original file and started the application with it, same error.

Do you have a functionnal configuration.json file to test it ?
Thanks

**Comment by PastaGringo** [comment]
I found the problem : 

line 19, add "," at the end of the line :

"Latitude": 48.753948**,** <------

testing with my  id now!

**Comment by PastaGringo** [comment]
Works like a charm :+1: 
Thanks again!

**Comment by bunzosteele** [comment]
:+1:
