### ISSUE TITLE
How to download updated version

### ISSUE THREAD

**Issue by KensonN** [bunzosteele/PokeWatch#25]
The download link seems to be the old version of the bot.

**Comment by bunzosteele** [comment]
I'm actively working on upgrading the bot right now, when I'm done for the night I'll post a new compiled download with an updated readme

**Comment by KensonN** [comment]
Alright. Thanks man! I've been using your bot to make my own city's [PokeWatch](http://www.twitter.com/pokewatchsj) and have been waiting for a fix on the crashes.

**Comment by bunzosteele** [comment]
Update has been posted
