### ISSUE TITLE
Visual Studio 2015 buidling help (Protobuf)

### ISSUE THREAD

**Issue by anton101101** [bunzosteele/PokeWatch#31]
Hi,

I'm having trouble building/running the solution in VS I have installed protobuf language service but I get the errors below appreciate any help with this 

https://i.gyazo.com/509970ade252d72d5dbba724c088d7c9.png
https://i.gyazo.com/39006013539b3879e28fd4d3e2db508a.png

Thanks

Anton

**Comment by JL907** [comment]
need reference paths to the lib folder and packages folder

**Comment by anton101101** [comment]
Thanks lemonlust all errors gone.
