### ISSUE TITLE
Is it possible for someone to see what's wrong with my .json?

### ISSUE THREAD

**Issue by dotheknifefight** [bunzosteele/PokeWatch#32]
So .json checkers are saying every line needs double quotes and it seems like I messed up on some syntax, but I basically edited the original, just swapping out values. I was careful not to delete any commas or brackets that was there. here is my file, maybe I'm missing something (or do I really have to go through and put double quotes around everything?)

`{

```
"PTCUsername": “ptcuser”,

"PTCPassword": “pw”,

"GAUsername": “username@gmail.com”,

"GAPassword": “pw“,

"TwitterConsumerToken": "token",

"TwitterConsumerSecret": "secret",

"TwitterAccessToken": "access",

"TwitterAccessSecret": "secret",

"RateLimit": 15,

"MinimumLifeExpectancy": 300,

"ExcludedPokemon": [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 42, 43, 46, 47, 48, 49, 54, 60, 69, 72, 73, 84, 85, 98, 102, 116, 118, 119, 120, 129, 133],

"PriorityPokemon": [3, 6, 9, 26, 31, 34, 35, 36, 40, 45, 62, 65, 68, 80, 83, 91, 92, 93, 94, 105, 106, 107, 108, 109, 110, 112, 113, 115, 122, 125, 126, 128, 130, 131, 132, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 149, 150, 151],

"TagPokemon": true,

"TagRegion": true,

"CustomTags": ["PokemonGo", “Wynwood”],

"RegularTweet": "A wild {0} appeared! It will be {1} {2} {3} until {4}. {5}",

"PriorityTweet": "BREAKING NEWS: {0} has appeared {1} {2} {3}! Hurry, it will vanish at {4}! {5}",

"PokemonOverrides": [{ "Kind": 16, "Display": "BirdBrain"}, { "Kind": 19, "Display":"BarneyMouse"}],

"Regions": [{

    "Name": “Panther Coffee“,

    "Prefix": "near”,

    "Suffix": "",

    "Locations": [{

        "Latitude": 25.7998834,

        "Longitude": -80.2014842

    }]

}, {

    "Name": “Brick House”,

    "Prefix": “around”,

    "Suffix": "",

    "Locations": [{

        "Latitude": 25.8031452,


        "Longitude": -80.2010509

    }]

}, {

    "Name": “Fireman Derek’s”,

    "Prefix": “near”,

    "Suffix": “Bake Shop“,

    "Locations": [{

        "Latitude": 25.8034033,

        "Longitude": -80.1974518

    }]

}, {

    "Name": “Kush”,

    "Prefix": “near”,

    "Suffix": “by Lokal“,

    "Locations": [{

        "Latitude": 25.7958924,

        "Longitude": -80.1968511

    }]

}, {

    "Name": “Mana”,

    "Prefix": “near”,

    "Suffix": ““,

    "Locations": [{

        "Latitude": 25.7980012,

        "Longitude": -80.2042594

    }]

}, {

    "Name": “J Wakefield”,

    "Prefix": “near”,

    "Suffix": “Brewing“,

    "Locations": [{

        "Latitude": 25.799612,

        "Longitude": -80.1997386

    }]

}, {

    "Name": “Wynwood Brewing”,

    "Prefix": “near”,

    "Suffix": “Co.“,

    "Locations": [{

        "Latitude": 25.800026,

        "Longitude": -80.2065807

    }]

}, {

    "Name": “The Wynwood Building”,

    "Prefix": “near”,

    "Suffix": ““,

    "Locations": [{


        "Latitude": 25.802608,
        "Longitude": -80.202031

    }]

}, {

    "Name": “Wynwood Walls”,

    "Prefix": “near”,

    "Suffix": ““,

    "Locations": [{

        "Latitude": 25.8011424,

        "Longitude": -80.2018629

    }]

}]
```

}`

**Comment by anton101101** [comment]
Here you go dude I replaced all your quotes you had left and right double quotation marks or something like that no sure what was going on also you had the following duplicate below which had no comma anyway. 
    "Regions": [{
            "Name": "Panther Coffee",
            "Prefix": "near",
            "Suffix": "",
            "Locations": [{
                "Latitude": 25.7998834,
                "Longitude": -80.2014842 
                **"Longitude": -80.2014842**

lint checked

{
    "PTCUsername": "ptcuser",
    "PTCPassword": "pw",
    "GAUsername": "username @gmail.com",
    "GAPassword": "pw",
    "TwitterConsumerToken": "token",
    "TwitterConsumerSecret": "secret",
    "TwitterAccessToken": "access",
    "TwitterAccessSecret": "secret",
    "RateLimit": 15,
    "MinimumLifeExpectancy": 300,
    "ExcludedPokemon": [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 42, 43, 46, 47, 48, 49, 54, 60, 69, 72, 73, 84, 85, 98, 102, 116, 118, 119, 120, 129, 133],
    "PriorityPokemon": [3, 6, 9, 26, 31, 34, 35, 36, 40, 45, 62, 65, 68, 80, 83, 91, 92, 93, 94, 105, 106, 107, 108, 109, 110, 112, 113, 115, 122, 125, 126, 128, 130, 131, 132, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 149, 150, 151],
    "TagPokemon": true,
    "TagRegion": true,
    "CustomTags": ["PokemonGo", "Wynwood"],
    "RegularTweet": "A wild {0} appeared! It will be {1} {2} {3} until {4}. {5}",
    "PriorityTweet": "BREAKING NEWS: {0} has appeared {1} {2} {3}! Hurry, it will vanish at {4}! {5}",
    "PokemonOverrides": [{
        "Kind": 16,
        "Display": "BirdBrain"
    }, {
        "Kind": 19,
        "Display": "BarneyMouse"
    }],
    "Regions": [{
        "Name": "Panther Coffee",
        "Prefix": "near",
        "Suffix": "",
        "Locations": [{
            "Latitude": 25.7998834,
            "Longitude": -80.2014842
        }]
    }, {
        "Name": "Brick House",
        "Prefix": "around",
        "Suffix": "",
        "Locations": [{
            "Latitude": 25.8031452,
            "Longitude": -80.2010509
        }]
    }, {
        "Name": "Fireman Derek’ s",
        "Prefix": "near",
        "Suffix": "Bake Shop",
        "Locations": [{
            "Latitude": 25.8034033,
            "Longitude": -80.1974518
        }]
    }, {
        "Name": "Kush",
        "Prefix": "near",
        "Suffix": "by Lokal",
        "Locations": [{
            "Latitude": 25.7958924,
            "Longitude": -80.1968511
        }]
    }, {
        "Name": "Mana",
        "Prefix": "near",
        "Suffix": "",
        "Locations": [{
            "Latitude": 25.7980012,
            "Longitude": -80.2042594
        }]
    }, {
        "Name": "J Wakefield",
        "Prefix": "near",
        "Suffix": "Brewing",
        "Locations": [{
            "Latitude": 25.799612,
            "Longitude": -80.1997386
        }]
    }, {
        "Name": "Wynwood Brewing",
        "Prefix": "near",
        "Suffix": "Co.",
        "Locations": [{
            "Latitude": 25.800026,
            "Longitude": -80.2065807
        }]
    }, {
        "Name": "The Wynwood Building",
        "Prefix": "near",
        "Suffix": "",
        "Locations": [{
            "Latitude": 25.802608,
            "Longitude": -80.202031
        }]
    }, {
        "Name": "Wynwood Walls",
        "Prefix": "near",
        "Suffix": "",
        "Locations": [{
            "Latitude": 25.8011424,
            "Longitude": -80.2018629
        }]
    }]
}

**Comment by PastaGringo** [comment]
You can test your json with http://jsonlint.com/ 👍

**Comment by cwliias** [comment]
} at the very end
You haven't closed your loop.
