### ISSUE TITLE
Create a guide on how to deploy PokeWatch to AWS

### ISSUE THREAD

**Issue by dislick** [bunzosteele/PokeWatch#39]
I am currently trying to figure out how to deploy this to AWS. If anyone already know how to do this, could you please write a quick guide for others?

**Comment by bunzosteele** [comment]
I plan on writing up a post this evening

**Comment by bunzosteele** [comment]
Delayed, but will still do.

**Comment by bunzosteele** [comment]
Super delayed by all the other stuff that has since happened. Also, AWS now requires a proxy to be a viable hosting solution. If I end up working something out for my own set up, I'll write up a guide on what I did
