### ISSUE TITLE
Pokevision

### ISSUE THREAD

**Issue by myfirstevercode** [bunzosteele/PokeWatch#41]
is it possible to put pokevision maps instead of google maps

https://pokevision.com/map/data/{location.Latitude}/{location.Longitude}

**Comment by bunzosteele** [comment]
imo this is substantially less mobile friendly, and could be problematic when pokevision servers are down. I'll look into adding an option to use this instead, but don't think it will replace as default

**Comment by RedSparr0w** [comment]
IMO `http://maps.apple.com/?q={location.Latitude},{location.Longitude}` would be better,
As it opens in default maps app for IOS or redirects to google maps link for anything else which means it should be pretty mobile friendly

Also i agree pokevision is not the best choice due to lack of stability.

Maybe it could have a config option like: ( {6} = Latitude, {7} = Longitude )

``` json
    "custom_link" : true,
    "custom_link_url" : "http://maps.apple.com/?q={6},{7}",
```

{5} = `custom_link_url`
-OR-

``` json
    "PriorityTweet": "BREAKING NEWS: {0} has appeared {1} {2} {3}! Hurry, it will vanish at {4}! http://maps.apple.com/?q={6},{7}",
```

**Comment by bunzosteele** [comment]
I would rather have toggles for which destination is tweeted than allow for customization. 
There is already an inherint risk that the bot will be abused to spam now that it has a fully customize able tweet content, but I feel like adding the ability to have it look like every other Pokewatch bot, but potentially link to a 3rd party site, a potentially malicious one, increases the danger

**Comment by RedSparr0w** [comment]
That is true, in that case i think the link should just be `http://maps.apple.com/?q={location.Latitude},{location.Longitude}` due to being more mobile friendly

**Comment by bunzosteele** [comment]
Google maps isn't mobile friendly? Also, the url you are suggesting is 404ing for me. (yes, i filled in values)

**Comment by RedSparr0w** [comment]
http://maps.apple.com/?q=40.720765,-73.996244 should be somewhere in New York.

Google maps is mobile friendly but i think it would be better to use apple maps due to it supporting the native maps app on IOS and android (I'm pretty sure)

**Comment by RedSparr0w** [comment]
Just tried tweeting with an apple URL and got stuck in a loop of loading Apple maps app.

When I switched back to Twitter it would keep opening the maps app until I closed and re opened the Twitter app.

So probably best to leave it as Google maps link.

**Comment by myfirstevercode** [comment]
Can atleast put at option? its better if you get a link from pokevision since its the exact position of the pokemon.. other than that this is great

**Comment by RedSparr0w** [comment]
Not sure what you mean? this is also the exact position of the pokemon.

**Comment by bunzosteele** [comment]
Option for pokevision included in new release
