### ISSUE TITLE
[ENHANCEMENT REQUEST] - Automatic Location Priority Maintenance

### ISSUE THREAD

**Issue by CaptWakaWaka** [bunzosteele/PokeWatch#56]
Using a local db, record the number of times each location was scanned and the number of times one or more pokemon were discovered in that location.  On later passes, reference this % to determine which locations to skip (based on a user threshold parameter).  E.g. location with a 20% yield only gets a 20% chance of being included in the current scan.

**Comment by CaptWakaWaka** [comment]
Thinking about this some more -- using shifted bits to record the recent yield for each location would do the trick.  I would try initial parameters of >40% yield = 100% chance, >20% yield = 80% chance, >=10% yield = 60% chance, <10% yield = 40% chance.  A "dead" or minimally active area still has a chance to heat up and get back in the game.  Anyway, this enhancement should enable a larger coverage area per bot with better time to expire.

**Comment by bunzosteele** [comment]
I think this is beyond the scope that I currently plan on taking this project
