### ISSUE TITLE
Active Window Issue

### ISSUE THREAD

**Issue by dpbuhlig** [bunzosteele/PokeWatch#57]
I am running this on my PC and I disabled the crash notification so that it can restart after a crash without user input but when it restarts it makes the twitter command prompt the active window and minimizes any full screen thing that I am doing. Is there a way to make it less obtrusive?

**Comment by bunzosteele** [comment]
Unfortunately, not that I am aware of.

**Comment by dpbuhlig** [comment]
I discovered that running the program on a separate user account is a good work around.
