### ISSUE TITLE
How can I change the name to the current location? 

### ISSUE THREAD

**Issue by hussainshamaas** [bunzosteele/PokeWatch#64]
Is there a way to get the address of the location instead of naming a location?

**Comment by bunzosteele** [comment]
I don't understand the use case for this

**Comment by hussainshamaas** [comment]
As in it will say "Pokemon is near 43 Charles Street .... " Then there will be no need to specify a "Name" for the region, rather it will be the exact area.

**Comment by RedSparr0w** [comment]
IMO i think this would be a lot of unnecessary work, as it isn't a major problem.

You could just specify more exact names for each area and split each area up into smaller areas.

``` json

    "Regions": [
        {
            "Name": "Takapuna",
            "Prefix": "near",
            "Suffix": "Boat Club",
            "Locations": [
                {
                    "Latitude": -36.78603697512318,
                    "Longitude": 174.7747564321353
                }
            ]
        },
        {
            "Name": "Takapuna",
            "Prefix": "close to",
            "Suffix": "Playground",
            "Locations": [
                {
                    "Latitude": -36.78793588967779,
                    "Longitude": 174.77473497390747
                }
            ]
        },
        {
            "Name": "Takapuna",
            "Prefix": "at the",
            "Suffix": "Rose Garden",
            "Locations": [
                {
                    "Latitude": -36.78714969441599,
                    "Longitude": 174.77115154336104
                }
            ]
        }
    ]
```

**Comment by bunzosteele** [comment]
In my mind it makes more sense to provide a name. Landmarks are more easily recognizable, and saying "Near the police station" will likely be more helpful than "204 Roosevelt Ave", particularly since the address will not actually be exact.
