### ISSUE TITLE
[Feature Request] Flag to launch certain config file

### ISSUE THREAD

**Issue by RedSparr0w** [bunzosteele/PokeWatch#67]
Would be handy to be able to launch with a certain config file,
so you could just create a couple of instances with different accounts/areas easier

**Comment by bunzosteele** [comment]
I was considering setting up PokewatchLauncher to manage multiple instances of Pokewatch, which would inherently include this.

**Comment by KensonN** [comment]
This would be incredibly useful now, with the reduced search radius creating more locations to scan.

**Comment by bunzosteele** [comment]
https://www.reddit.com/r/pokewatch/comments/4xioal/pokewatch_v4/
