### ISSUE TITLE
Command Prompt opens and closes immediately

### ISSUE THREAD

**Issue by screenhunter** [bunzosteele/PokeWatch#7]
Whenever i run the app, it just opens 2 instances of command prompt and then immediately closes

I have attached the configuration file without the passwords, as its the only thing ive changed in the source code
[Configuration.txt](https://github.com/bunzosteele/PokeWatch/files/380578/Configuration.txt)

**Comment by bunzosteele** [comment]
Something is going wrong during start up, most likely with authenticating either your pogo account or your twitter account, can you attach your log.txt file?

**Comment by screenhunter** [comment]
Actually, I didn't even notice there was a log.txt account, and it turns out my twitter account was not working. Thanks!
