### ISSUE TITLE
Special characters like 'ß' are now � since V3

### ISSUE THREAD

**Issue by klepek42** [bunzosteele/PokeWatch#72]
Since V3 I experience that special characters are not showen correctly in the tweets. 
How is this possible? I would be happy about a fix.

Here is an example tweet: https://twitter.com/pokewatch_hochd/status/760576448826642432

**Comment by bunzosteele** [comment]
Undid the change in v3, so anything broken by v3 should now be working in v4, but there are still a few invalid characters that were broken before v3.
https://www.reddit.com/r/pokewatch/comments/4xioal/pokewatch_v4/

**Comment by bunzosteele** [comment]
Duplicate of Issue #59
