### ISSUE TITLE
Scan time 10s now instead of 5s

### ISSUE THREAD

**Issue by RedSparr0w** [bunzosteele/PokeWatch#73]
[link](https://www.reddit.com/r/pokemongo/comments/4vvpbw/niantic_is_upping_the_scan_refresh_rate_to_break/), also all pokemon seem to show up twice now due to the increase in time needed between scans

**Comment by bunzosteele** [comment]
In order for users to accommodate this, they will likely want an increase in the number of bots to reduce scan delay. This is starting to get out of hand, and I plan on making changes to the program to alleviate this. I plan on having a single PokewatchLauncher, with a single config file manage multiple  bots. This will involve some config changes so I thought I would make you  ( @RedSparr0w ) aware of my plans. 
Here's what I plan to have configs looking like once I make the changes:

```
{

"PoGoAccounts": [{
    "PTCUsername": "PTCUsername1",
    "PTCPassword": "PTCPassword1",
    "GAUsername": "GA1",
    "GAPassword": "GA1",
},{
    "PTCUsername": "PTC2",
    "PTCPassword": "PTC2",
    "GAUsername": "GA2",
    "GAPassword": "GA2",
}]
"TwitterConsumerToken": "CONSUMERKEY",
"TwitterConsumerSecret": "CONSUMERSECRET",
"TwitterAccessToken": "ACCESSTOKEN",
"TwitterAccessSecret": "ACCESSSECRET",
"RateLimit": 0,
"MinimumLifeExpectancy": 300,
"ExcludedPokemon": [10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 29, 30, 32, 33, 35, 39, 41, 42, 43, 46, 47, 48, 49, 52, 54, 56, 60, 63, 69, 72, 73, 74, 86, 90, 92, 96, 98, 100, 116, 118, 120, 125, 129, 133],
"PriorityPokemon": [3, 6, 9, 26, 38, 59, 62, 65, 68, 78, 80, 94, 103, 105, 106, 107, 112, 113, 115, 122, 130, 131, 132, 142, 143, 144, 145, 146, 149, 150, 151],
"Pokevision": false,
"TagPokemon": true,
"TagRegion": true,
"CustomTags": ["PokemonGo", "Bellingham"],
"RegularTweet": "A wild {0} appeared! It will be {1} {2} {3} until {4}. {5}",
"PriorityTweet": "BREAKING NEWS: {0} has appeared {1} {2} {3}! Hurry, it will vanish at {4}! {5}",
"PokemonOverrides": [{ "Kind": 16, "Display": "BirdBrain"}, { "Kind": 19, "Display":"BarneyMouse"}],
"Regions": [{
    "Name": "Highschool",
    "Prefix": "around the",
    "Suffix": "",
    "Exclusions": [1, 2, 3],
    "Inclusions": [10, 11, 13],
    "Locations": [{
        "Latitude": 48.757564,
        "Longitude": -122.474716
    }, {
        "Latitude": 48.75755,
        "Longitude": -122.47183
    }, {
        "Latitude": 48.755315,
        "Longitude": -122.471862
    }]
}, {
    "Name": "Downtown",
    "Prefix": "in the",
    "Suffix": "area",
    "Exclusions": [4, 5, 6],
    "Inclusions": [10, 11, 13],
    "Locations": [{
        "Latitude": 48.747813,
        "Longitude": -122.478256
    }, {
        "Latitude": 48.748513,
        "Longitude": -122.479576
    }, {
        "Latitude": 48.749277,
        "Longitude": -122.478138
    }, {
        "Latitude": 48.750331,
        "Longitude": -122.476668
    }, {
        "Latitude": 48.749831,
        "Longitude": -122.474853
    }]
}, {
    "Name": "Aslan Brewing",
    "Prefix": "near the",
    "Suffix": "Company",
    "Exclusions": [7, 8, 9],
    "Inclusions": [10, 11, 13, 35],
    "Locations": [{
        "Latitude": 48.748414,
        "Longitude": -122.474694
    }]
}]
}
```

The key difference being that we now take in a list of PTC accounts, and different regions have overrides to the general excluded pokemon list. Allowing you to ignore nests or particularly care about a certain pokemon in an area but not others. The ConfigGenerator could likely just supply empty lists or nothing for Exclusions and Inclusions, as the use of them seems to be generally pretty niche, but the change to PTC accounts would be pretty breaking for the current state of things.

**Comment by lennon681** [comment]
Do you have an ETA on when the new config will be supported?  I plan to generate new config files tonight so if it will be very soon I'll generate them in the new format (which will be awesome!).

**Comment by RedSparr0w** [comment]
@bunzosteele Will update it to work with new config format in the next few days. hopefully the bots are all working by then XD

**Comment by bunzosteele** [comment]
Yep, I've paused working on it in the mean time

**Comment by bunzosteele** [comment]
https://www.reddit.com/r/pokewatch/comments/4xioal/pokewatch_v4/
