### ISSUE TITLE
Nothing being found

### ISSUE THREAD

**Issue by lennon681** [bunzosteele/PokeWatch#75]
None of my 6 instances are finding any pokemon (good, bad, or otherwise).

Looks like it may be related to this post:
https://www.reddit.com/r/pokemongodev/comments/4w0mtr/getting_0_pokemon_upserted_in_last_few_minutes/

**Comment by hussainshamaas** [comment]
It seems as if Niantic is obfuscating the api answers. According to sources online, it means we have to update the POGOProtos and implement the new hash: b1f2bf509a025b7cd76e1c484e2a24411c50f0612

**Comment by KensonN** [comment]
Happening to me as well. 12 bots with 50 locations each haven't found anything for 3 hours.

**Comment by bunzosteele** [comment]
Yep, pokewatch and pretty much all pogo bots will be down for awhile.

**Comment by DonaldBough** [comment]
Any idea if any other POGO api's have gotten around this?

**Comment by bunzosteele** [comment]
It hasn't been cracked yet. /r/pokemongodev will explode when it has.

**Comment by lennon681** [comment]
It's ready!! :) https://github.com/keyphact/pgoapi

**Comment by bunzosteele** [comment]
https://www.reddit.com/r/pokewatch/comments/4xioal/pokewatch_v4/
