### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by elit3ge** [bunzosteele/PokeWatch#77]
Here is the new api data.

https://github.com/keyphact/pgoapi

**Comment by elit3ge** [comment]
Is this project being worked on anymore?

**Comment by tcoliver** [comment]
As far as I know, yes...
https://www.reddit.com/r/pokewatch/comments/4wusan/state_of_pokewatch/

**Comment by elit3ge** [comment]
I see that there has been an update, will it be compiled soon?

**Comment by bunzosteele** [comment]
https://www.reddit.com/r/pokewatch/comments/4xioal/pokewatch_v4/

**Comment by elit3ge** [comment]
Awesome thanks :D
