### ISSUE TITLE
Scan 200m with new API???

### ISSUE THREAD

**Issue by KensonN** [bunzosteele/PokeWatch#78]
https://www.reddit.com/r/pokemongodev/comments/4wyldi/psa_to_data_miners_you_can_scan_200m_circles/

**Comment by RedSparr0w** [comment]
unfortunately not, 200m is the nearby. so if you just want to know that xxx is nearby it would be fine, but if you wanted to know the exact location then you need to use 70m circles.

**Comment by RedSparr0w** [comment]
[this comment makes a good point though](https://www.reddit.com/r/pokemongodev/comments/4wyldi/psa_to_data_miners_you_can_scan_200m_circles/d6bkb29)

**Comment by bunzosteele** [comment]
Feel free to reopen if you disagree, but imo the cost of not implementing an algorithm like this isn't high enough to justify the venture.
