### ISSUE TITLE
map menu unusable with to many locations (needs to scroll)

### ISSUE THREAD

**Issue by tcoliver** [bunzosteele/PokeWatch#89]
## Issue/Bug

When using more than 15 areas/regions, the earliest created areas cannot fit onscreen in the map menu (right click menu). This wasn't a problem when we had multiple config files, as it was unlikely for one worker to surpass 15 locations. But now that all workers are in the same config, having more than 15 areas is very easy to do. As there is no way to scroll up on the map menu, there is no way to add locations to the earliest created areas.
## Suggested Solution

In the most recent commit of ConfigGenerator.html, I noticed that we can now scroll the sidebar menu. How difficult would it be to add the same scroll function to the map menu?
## Screenshot

![screenshot](https://i.imgur.com/TW1n8QG.png)

**Comment by bunzosteele** [comment]
Temporary workaround to this is to be sure to tag your areas in order, the newest area will always be on the bottom.

**Comment by tcoliver** [comment]
Yea, that's what I have been doing, which works well enough. Another way is to recreate the area further down, then manually merge them in the config file. Still, this would be a nice addition.

BTW---Thanks for all the hard work. I know it's not an easy task to keep something like this going!
