### ISSUE TITLE
ExcludedPokemon - Not fuctioning as expected

### ISSUE THREAD

**Issue by NX3** [bunzosteele/PokeWatch#92]
I've removed Abra and Eevee from the excluded list but I keep seeing them excluded.

"30/08/2016 21:29:59: [!]Excluded: Eevee (799 seconds): 51.449628,-2.594482"

When I add to the list that seems to work and changes to priority list. Its picking up the json file from the folder I'm editing, single user of the file with nothing else using it. I can't see why it excluded's them when they aren't on the list anymore.

**Comment by NX3** [comment]
This issue is caused by ConfigGenerator.html spacing one entry per line for excluded pokemon

**Comment by RedSparr0w** [comment]
hmm, not sure why this would impact it?
seems to be working fine for me when i add/remove pokemon from the excluded/priority list.

**Comment by bunzosteele** [comment]
spacing shouldnt impact this. you may want to double check that you dont have any region specific overrides. ctrl+f the pokedexid, and see if there are any unexpected hits

**Comment by NX3** [comment]
I've worked out the issue was Notepad++ caching files I'm editing was the issue. Sorry, just took a while to figure out what it was doing.
